var jednostka=[
	{},//puste
    {
    	"nazwa":"Miotacz Toporów",
        "hp":"100",
        "atk":"55",
        "def":"60",
		"luck":"20",
		"koszt":"1000",
		"nazwaObrazka":"topor"
    },
    {
        "nazwa":"Pikinier",
        "hp":"70",
        "atk":"65",
        "def":"60",
		"luck":"40",
		"koszt":"1200",
		"nazwaObrazka":"pikinier"
    },
	    {
	    "nazwa":"Łucznik",
        "hp":"30",
        "atk":"95",
        "def":"60",
		"luck":"60",
		"koszt":"1100",
		"nazwaObrazka":"lucznik"
    },
	    {
	    "nazwa":"Kawaleria",
        "hp":"90",
        "atk":"67",
        "def":"65",
		"luck":"46",
		"koszt":"1700",
		"nazwaObrazka":"kawaleria"
		
    },
	    {
	    "nazwa":"Ciężka Kawaleria",
        "hp":"80",
        "atk":"95",
        "def":"50",
		"luck":"60",
		"koszt":"2200",
		"nazwaObrazka":"Ckawaleria"
    },
	    {
	    "nazwa":"Rycerz",
        "hp":"130",
        "atk":"165",
        "def":"160",
		"luck":"140",
		"koszt":"3200",
		"nazwaObrazka":"rycerz"
		
    },
	    {
	    "nazwa":"Kleryk",
        "hp":"14",
        "atk":"25",
        "def":"20",
		"luck":"240",
		"koszt":"700",
		"nazwaObrazka":"kleryk"
    },
	    {
	    "nazwa":"Dowódca",
        "hp":"430",
        "atk":"465",
        "def":"360",
		"luck":"540",
		"koszt":"3200"		,
		"nazwaObrazka":"dowodzca"
    },
	    {
	    "nazwa":"Wilkor",
        "hp":"404",
        "atk":"665",
        "def":"360",
		"luck":"440",
		"koszt":"4200",
		"nazwaObrazka":"wilkor"
    }
];